--=========Creación de Tablas=========--

--Tabla CARRITO
CREATE TABLE CARRITO (
    "ID_CA" NUMBER NOT NULL,
    "FEC_CRE_CA" DATE NOT NULL,
    "CLIENTE_RUN_CLI" NUMBER NOT NULL,

    CONSTRAINT "CARRITO_PK" PRIMARY KEY ("ID_CA"),
    USING INDEX)
;

--Tabla CLIENTE
CREATE TABLE "CLIENTE" (
    "RUN_CLI" NUMBER NOT NULL,
	"DV_RUN_CLI" CHAR(1) NOT NULL,
	"NOMBRE_CLI" VARCHAR(100) NOT NULL,
	"FECHA_NAC_CLI" DATE NOT NULL,
	"DIREC_CLI" VARCHAR(150) NOT NULL,
	"FECHA_REG_CLI" DATE,

	CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("RUN_CLI"))
;
--Tabla COMPRA
CREATE TABLE "COMPRA" (
    "COD_COM" NUMBER NOT NULL,
	"DESC_COM" VARCHAR(350),
	"TOTAL_SIN_IVA" NUMBER NOT NULL,
	"VALOR_IVA" NUMBER NOT NULL,
	"TOTAL_CON_IVA" NUMBER NOT NULL,
	"FECHA_COM" DATE NOT NULL,
	"CLIENTE_RUN_CLI" NUMBER NOT NULL,
	"CARRITO_ID_CA" NUMBER NOT NULL,

	CONSTRAINT "COMPRA_PK" PRIMARY KEY ("COD_COM"))
;
--TABLA DETALLE_CARRITO
CREATE TABLE "DETALLE_CARRITO" (
	"ID_DETA_CA" NUMBER NOT NULL,
	"CARRITO_ID_CA" NUMBER NOT NULL,
	"PRODUCTO_ID_PRO" NUMBER NOT NULL,
	"CANT_PRO" NUMBER NOT NULL,

    CONSTRAINT "DETALLE_CARRITO_PK" PRIMARY KEY ("ID_DETA_CA"))

;
--TABLA ENTREGA
CREATE TABLE "ENTREGA" (
	"ID_ENTREGA" NUMBER NOT NULL,
	"ESTADO_ENT" VARCHAR(15) NOT NULL,
	"FECHA_ENT_APROX" DATE NOT NULL,
	"FECHA_ENT_FIN" DATE NOT NULL,
	"COMPRA_COD_COM" NUMBER NOT NULL,
	"REPARTIDOR_RUN" NUMBER,

	CONSTRAINT "ENTREGA_PK" PRIMARY KEY ("ID_ENTREGA"))
;

--Tabla REPARTIDOR
CREATE TABLE "REPARTIDOR"(
    "RUN_REPARTIDOR" NUMBER NOT NULL,
	"DV_RUN_REPAR" CHAR(1) NOT NULL,
	"NOMBRE_REPAR" VARCHAR(200) NOT NULL,
	"FECHA_CONTRATO_REPAR" DATE NOT NULL,
	"FONO_REPAR" NUMBER NOT NULL,

    CONSTRAINT "REPARTIDOR_PK" PRIMARY KEY ("RUN_REPARTIDOR") )
;

--Tabla PRODUCTO
CREATE TABLE "PRODUCTO" (
	"ID_PRO" NUMBER NOT NULL,
	"NOM_PRO" VARCHAR(150) NOT NULL,
	"DESC_PRO" VARCHAR(350) NOT NULL,
	"PRE_PRO" NUMBER NOT NULL,
	"FRANQUICIA_PRO" VARCHAR(30) NOT NULL,
	"OFER_PRO" BINARY_FLOAT,
	"FOTO_PRO" VARCHAR(350),
	"STOCK" NUMBER NOT NULL,

	CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID_PRO"))
;

--=========Creación de Llaves Foráneas=========--
ALTER TABLE "ENTREGA" ADD CONSTRAINT "ENTREGA_COMPRA_FK" FOREIGN KEY ("COMPRA_COD_COM")
	REFERENCES "COMPRA" ("COD_COM");

ALTER TABLE "ENTREGA" ADD CONSTRAINT "ENTREGA_REPARTIDOR_FK" FOREIGN KEY ("REPARTIDOR_RUN")
	REFERENCES "REPARTIDOR" ("RUN_REPARTIDOR");

ALTER TABLE "DETALLE_CARRITO" ADD CONSTRAINT "DETALLE_CARRITO_CARRITO_FK" FOREIGN KEY ("CARRITO_ID_CA")
	REFERENCES "CARRITO" ("ID_CA");

ALTER TABLE "DETALLE_CARRITO" ADD CONSTRAINT "DETALLE_CARRITO_PRODUCTO_FK" FOREIGN KEY ("PRODUCTO_ID_PRO")
	REFERENCES "PRODUCTO" ("ID_PRO");

ALTER TABLE "COMPRA" ADD CONSTRAINT "COMPRA_CLIENTE_FK" FOREIGN KEY ("CLIENTE_RUN_CLI")
    REFERENCES "CLIENTE" ("RUN_CLI");

ALTER TABLE "COMPRA" ADD CONSTRAINT "COMPRA_CARRITO_FK" FOREIGN KEY ("CARRITO_ID_CA")
    REFERENCES "CARRITO" ("ID_CA");

ALTER TABLE "CARRITO" ADD CONSTRAINT "CARRITO_CLIENTE_FK" FOREIGN KEY ("CLIENTE_RUN_CLI")
    REFERENCES "CLIENTE" ("RUN_CLI");