--Creación del package

CREATE OR REPLACE PACKAGE PKG_KPI_CLIENTES_ENTREGAS IS
    PROCEDURE PROC_KPI1_REGISTROS;
    PROCEDURE PROC_KPI5_ENTREGAS;
    PROCEDURE PROC_KPI6_RECURRENCIA;

    PROCEDURE RUN_ALL;
END PKG_KPI_CLIENTES_ENTREGAS;
/

--creación del cuerpo del package

CREATE OR REPLACE PACKAGE BODY PKG_KPI_CLIENTES_ENTREGAS IS

-- =================================================================
--PROCEDURE 1
-- =================================================================
CREATE OR REPLACE PROCEDURE PROC_REGISTROS_POR_ANIO IS

--==================Definicion de variables==================--

--variable para manejo de errores
C_PROC_NAME CONSTANT VARCHAR2(30) := 'PROC_REGISTROS_POR_ANIO';

--Record para almacenar años y conteos
TYPE KPI1_REC IS RECORD (
    ANIO_REC KPI_1.ANIO%TYPE,
    TOT_REGISTROS_REC KPI_1.TOTAL_REGISTROS%TYPE
);
-- Colección para resultados
TYPE KPI1_ARRAY IS TABLE OF KPI1_REC;

-- Colección de los resultados.
ARRAY_RESULTADOS KPI1_ARRAY;

--==================Inicio de los procesos==================--

BEGIN
--vaciar tabla destino
DELETE FROM KPI_1;

--clasificación y conteo
SELECT
    CASE
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) <= 2020 THEN '2020 o antes'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2021 THEN '2021'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2022 THEN '2022'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2023 THEN '2023'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2024 THEN '2024'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = EXTRACT(YEAR FROM SYSDATE) THEN 'Este año'
        ELSE NULL
    END AS ANIO_REC,
    COUNT(c.RUN_CLI) AS TOT_REGISTROS_REC

BULK COLLECT INTO ARRAY_RESULTADOS

FROM
    CLIENTE c
    WHERE
    --Se revisa que el año sea válido
        c.FECHA_REG_CLI IS NOT NULL
        AND EXTRACT(YEAR FROM c.FECHA_REG_CLI) <= 2025

GROUP BY
    CASE
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) <= 2020 THEN '2020 o antes'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2021 THEN '2021'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2022 THEN '2022'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2023 THEN '2023'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2024 THEN '2024'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = EXTRACT(YEAR FROM SYSDATE) THEN 'Este año'
        ELSE NULL
    END
HAVING
    CASE ... END IS NOT NULL;

-- Inserción de los datos recolectados
IF ARRAY_RESULTADOS.COUNT > 0 THEN
    FORALL i IN ARRAY_RESULTADOS.FIRST .. ARRAY_RESULTADOS.LAST
        INSERT INTO KPI_1 (ANIO, TOTAL_REGISTROS)
        VALUES (ARRAY_RESULTADOS(i).ANIO_REC, ARRAY_RESULTADOS(i).TOT_REGISTROS_REC);
END IF;

--==================Manejo de excepciones==================--
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('--- ERROR EN EL PROCEDIMIENTO KPI 1 ---');
        DBMS_OUTPUT.PUT_LINE('Procedimiento: ' || C_PROC_NAME);
        DBMS_OUTPUT.PUT_LINE('Código SQL: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('Mensaje SQL: ' || SQLERRM);
        RAISE;

END PROC_REGISTROS_POR_ANIO;
/
-- =================================================================
--PROCEDURE 5
-- =================================================================
CREATE OR REPLACE PROCEDURE PROC_KPI5_TASA_ENTREGAS IS

--==================Definicion de variables==================--

C_PROC_NAME CONSTANT VARCHAR2(30) := 'PROC_KPI5_TASA_ENTREGAS';

-- RECORD para variables
TYPE KPI5_REC IS RECORD (
    PERIODO             KPI_5.PERIODO%TYPE,
    TASA_EXITOSAS       KPI_5.TASA_EXITOSAS%TYPE,
    VARIACION_TASA      KPI_5.VARIACION_TASA%TYPE,
    FECHA_ACTUALIZACION KPI_5.FECHA_ACTUALIZACION%TYPE
);

-- Colección para resultados
TYPE kpi5_array IS TABLE OF KPI5_REC;
RESULTADOS_KPI5 kpi5_array;

--==================Inicio de los procesos==================--
BEGIN
-- Limpieza de tabla de destino
DELETE FROM KPI_5;

-- Cálculo de la tasa de entregas exitosas
WITH ENTREGAS_MENSUALES AS (
    SELECT
        TRUNC(FECHA_ENT_FIN, 'MM') AS MES,
        COUNT(ID_ENTREGA) AS TOTAL_ENTREGAS_PROCESADAS,
        SUM(CASE WHEN UPPER(ESTADO_ENT) = 'ENTREGADO' THEN 1 ELSE 0 END) AS ENTREGAS_EXITOSAS
    FROM
        ENTREGA
    WHERE
        FECHA_ENT_FIN IS NOT NULL
        AND UPPER(ESTADO_ENT) IN ('ENTREGADO', 'ENTREGA FALLIDA')
        AND FECHA_ENT_FIN >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11)
    GROUP BY
        TRUNC(FECHA_ENT_FIN, 'MM')
),

TASAS_CALCULADAS AS (
    SELECT
        MES,
        CASE 
            WHEN EM.TOTAL_ENTREGAS_PROCESADAS > 0
            THEN ROUND((EM.ENTREGAS_EXITOSAS / EM.TOTAL_ENTREGAS_PROCESADAS) * 100, 2)
            ELSE 0 
        END AS TASA_ACTUAL,
        LAG(
            CASE WHEN EM.TOTAL_ENTREGAS_PROCESADAS > 0 THEN ROUND((EM.ENTREGAS_EXITOSAS / EM.TOTAL_ENTREGAS_PROCESADAS) * 100, 2) ELSE 0 END,
            1,
            NULL
        ) OVER (ORDER BY MES) AS TASA_ANTERIOR
    FROM
        ENTREGAS_MENSUALES EM
)

-- Recolección de resultados
SELECT
    TO_CHAR(TC.MES, 'Month YYYY', 'NLS_DATE_LANGUAGE=SPANISH') AS PERIODO,
    TC.TASA_ACTUAL AS TASA_EXITOSAS,
    CASE
        WHEN TC.TASA_ANTERIOR IS NOT NULL
        THEN ROUND(TC.TASA_ACTUAL - TC.TASA_ANTERIOR, 2)
        ELSE NULL
    END AS VARIACION_TASA,
    SYSDATE AS FECHA_ACTUALIZACION
BULK COLLECT INTO RESULTADOS_KPI5
FROM
    TASAS_CALCULADAS TC
ORDER BY
    TC.MES;

-- Inserción de resultados
IF RESULTADOS_KPI5.COUNT > 0 THEN
    FORALL i IN RESULTADOS_KPI5.FIRST .. RESULTADOS_KPI5.LAST
        INSERT INTO KPI_5 (
            PERIODO, TASA_EXITOSAS, VARIACION_TASA, FECHA_ACTUALIZACION
        )
        VALUES (
            RESULTADOS_KPI5(i).PERIODO,
            RESULTADOS_KPI5(i).TASA_EXITOSAS,
            RESULTADOS_KPI5(i).VARIACION_TASA,
            RESULTADOS_KPI5(i).FECHA_ACTUALIZACION
        );
END IF;

EXCEPTION
WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('--- ERROR EN EL PROCEDIMIENTO KPI 5 ---');
    DBMS_OUTPUT.PUT_LINE('Procedimiento: ' || C_PROC_NAME);
    DBMS_OUTPUT.PUT_LINE('Código SQL: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('Mensaje SQL: ' || SQLERRM);
    RAISE;
END PROC_KPI5_TASA_ENTREGAS;
/

-- =================================================================
--PROCEDURE 6
-- =================================================================
CREATE OR REPLACE PROCEDURE PROC_KPI6_RECURRENCIA IS

--==================Definicion de variables==================--

C_PROC_NAME CONSTANT VARCHAR2(30) := 'PROC_KPI6_RECURRENCIA';

-- record para variables
TYPE KPI_REC IS RECORD (
    ANIO                KPI_6.ANIO%TYPE,
    TOTAL_CLIENTES_UNQ  KPI_6.TOTAL_CLIENTES_UNQ%TYPE,
    TASA_RECURRENCIA    KPI_6.TASA_RECURRENCIA%TYPE,
    VARIACION_TASA      KPI_6.VARIACION_TASA%TYPE,
    FECHA_ACTUALIZACION KPI_6.FECHA_ACTUALIZACION%TYPE
);

-- Colección para resultados
TYPE kpi6_array IS TABLE OF KPI_REC;
RESULTADOS_KPI6 kpi6_array;

--==================Inicio de los procesos==================--
BEGIN
-- Limpieza de tabla de destino
DELETE FROM KPI_6;

-- 2. Cálculo Masivo con SQL (Agregación y Analíticas)
WITH FRECUENCIA_ANUAL AS (
    SELECT
        TO_CHAR(FECHA_COM, 'YYYY') AS ANIO,
        CLIENTE_RUN_CLI,
        COUNT(COD_COM) AS COMPRAS_TOTALES
    FROM
        COMPRA
    GROUP BY
        TO_CHAR(FECHA_COM, 'YYYY'), CLIENTE_RUN_CLI
),

TASAS_ANUALES AS (
    SELECT
        FA.ANIO,
        COUNT(FA.CLIENTE_RUN_CLI) AS TOTAL_CLIENTES_UNQ,
        SUM(CASE WHEN FA.COMPRAS_TOTALES > 1 THEN 1 ELSE 0 END) AS CLIENTES_RECURRENTES,
        ROUND((SUM(CASE WHEN FA.COMPRAS_TOTALES > 1 THEN 1 ELSE 0 END) / COUNT(FA.CLIENTE_RUN_CLI)) * 100, 2) AS TASA_ACTUAL
    FROM
        FRECUENCIA_ANUAL FA
    GROUP BY
        FA.ANIO
    ORDER BY
        FA.ANIO
)
--Colección de resultados
SELECT
    TA.ANIO AS ANIO,
    TA.TOTAL_CLIENTES_UNQ AS TOTAL_CLIENTES_UNQ,
    TA.TASA_ACTUAL AS TASA_RECURRENCIA,
    CASE 
        WHEN LAG(TA.TASA_ACTUAL, 1, NULL) OVER (ORDER BY TA.ANIO) IS NOT NULL
        THEN ROUND(TA.TASA_ACTUAL - LAG(TA.TASA_ACTUAL, 1) OVER (ORDER BY TA.ANIO), 2)
        ELSE NULL
    END AS VARIACION_TASA,
    SYSDATE AS FECHA_ACTUALIZACION
BULK COLLECT INTO RESULTADOS_KPI6
FROM
    TASAS_ANUALES TA;
    
-- Inserción de resultados
IF RESULTADOS_KPI6.COUNT > 0 THEN
    FORALL i IN RESULTADOS_KPI6.FIRST .. RESULTADOS_KPI6.LAST
        INSERT INTO KPI_6 (
            ANIO, TOTAL_CLIENTES_UNQ, TASA_RECURRENCIA, VARIACION_TASA, FECHA_ACTUALIZACION
        )
        VALUES (
            RESULTADOS_KPI6(i).ANIO,
            RESULTADOS_KPI6(i).TOTAL_CLIENTES_UNQ,
            RESULTADOS_KPI6(i).TASA_RECURRENCIA,
            RESULTADOS_KPI6(i).VARIACION_TASA,
            RESULTADOS_KPI6(i).FECHA_ACTUALIZACION
        );
END IF;

EXCEPTION
WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('--- ERROR EN EL PROCEDIMIENTO KPI 6 ---');
    DBMS_OUTPUT.PUT_LINE('Procedimiento: ' || C_PROC_NAME);
    DBMS_OUTPUT.PUT_LINE('Código SQL: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('Mensaje SQL: ' || SQLERRM);
    RAISE;
END PROC_KPI6_RECURRENCIA

-- =================================================================
-- RUN_ALL
-- =================================================================
PROCEDURE RUN_ALL IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- Iniciando PKG_KPI_CLIENTES_ENTREGAS ---');
    PROC_KPI1_REGISTROS;
    PROC_KPI5_ENTREGAS;
    PROC_KPI6_RECURRENCIA;
    DBMS_OUTPUT.PUT_LINE('--- PKG_KPI_CLIENTES_ENTREGAS Finalizado ---');
END RUN_ALL;

END PKG_KPI_CLIENTES_ENTREGAS;
/