CREATE OR REPLACE PROCEDURE PROC_REGISTROS_POR_ANIO IS

--==================Definicion de variables==================--

--variable para manejo de errores
C_PROC_NAME CONSTANT VARCHAR2(30) := 'PROC_REGISTROS_POR_ANIO';

--Record para almacenar años y conteos
TYPE KPI1_REC IS RECORD (
    ANIO_REC KPI_1.ANIO%TYPE,
    TOT_REGISTROS_REC KPI_1.TOTAL_REGISTROS%TYPE
);
-- Colección para resultados
TYPE KPI1_ARRAY IS TABLE OF KPI1_REC;

-- Colección de los resultados.
ARRAY_RESULTADOS KPI1_ARRAY;

--==================Inicio de los procesos==================--

BEGIN
--vaciar tabla destino
DELETE FROM KPI_1;

--clasificación y conteo
SELECT
    CASE
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) <= 2020 THEN '2020 o antes'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2021 THEN '2021'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2022 THEN '2022'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2023 THEN '2023'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2024 THEN '2024'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = EXTRACT(YEAR FROM SYSDATE) THEN 'Este año'
        ELSE NULL
    END AS ANIO_REC,
    COUNT(c.RUN_CLI) AS TOT_REGISTROS_REC

BULK COLLECT INTO ARRAY_RESULTADOS

FROM
    CLIENTE c
    WHERE
    --Se revisa que el año sea válido
        c.FECHA_REG_CLI IS NOT NULL
        AND EXTRACT(YEAR FROM c.FECHA_REG_CLI) <= 2025

GROUP BY
    CASE
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) <= 2020 THEN '2020 o antes'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2021 THEN '2021'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2022 THEN '2022'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2023 THEN '2023'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = 2024 THEN '2024'
        WHEN EXTRACT(YEAR FROM c.FECHA_REG_CLI) = EXTRACT(YEAR FROM SYSDATE) THEN 'Este año'
        ELSE NULL
    END
HAVING
    CASE ... END IS NOT NULL;

-- Inserción de los datos recolectados
IF ARRAY_RESULTADOS.COUNT > 0 THEN
    FORALL i IN ARRAY_RESULTADOS.FIRST .. ARRAY_RESULTADOS.LAST
        INSERT INTO KPI_1 (ANIO, TOTAL_REGISTROS)
        VALUES (ARRAY_RESULTADOS(i).ANIO_REC, ARRAY_RESULTADOS(i).TOT_REGISTROS_REC);
END IF;

--==================Manejo de excepciones==================--
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('--- ERROR EN EL PROCEDIMIENTO KPI 1 ---');
        DBMS_OUTPUT.PUT_LINE('Procedimiento: ' || C_PROC_NAME);
        DBMS_OUTPUT.PUT_LINE('Código SQL: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('Mensaje SQL: ' || SQLERRM);
        RAISE;

END PROC_REGISTROS_POR_ANIO;
/