CREATE OR REPLACE PROCEDURE PROC_KPI7_CONVERSION IS

--==================Definicion de variables==================--

C_PROC_NAME CONSTANT VARCHAR2(30) := 'PROC_KPI7_CONVERSION';

-- record para variables
TYPE KPI7_REC IS RECORD (
    PERIODO                     KPI_7.PERIODO%TYPE,
    TOTAL_CARRITOS              KPI_7.TOTAL_CARRITOS%TYPE,
    TASA_CONVERSION             KPI_7.TASA_CONVERSION%TYPE,
    VARIACION_TASA              KPI_7.VARIACION_TASA%TYPE,
    FECHA_ACTUALIZACION         KPI_7.FECHA_ACTUALIZACION%TYPE
);

-- Colección para resultados
TYPE tkpi7_array IS TABLE OF KPI7_REC;
RESULTADOS_KPI7 kpi7_array;

--==================Inicio de los procesos==================--
BEGIN
-- Limpieza de tabla de destino
DELETE FROM KPI_7;

-- Cálculo
WITH CONVERSION_MENSUAL AS (
    SELECT
        TRUNC(c.FEC_CRE_CA, 'MM') AS MES,
        COUNT(c.ID_CA) AS TOTAL_CARRITOS,
        SUM(CASE WHEN comp.COD_COM IS NOT NULL THEN 1 ELSE 0 END) AS CARRITOS_CONVERTIDOS
    FROM
        CARRITO c
    LEFT JOIN
        COMPRA comp ON c.ID_CA = comp.CARRITO_ID_CA
    WHERE
        c.FEC_CRE_CA >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11)
    GROUP BY
        TRUNC(c.FEC_CRE_CA, 'MM')
),
TASAS_CALCULADAS AS (
    SELECT
        CM.MES,
        CM.TOTAL_CARRITOS,
        CASE
            WHEN CM.TOTAL_CARRITOS > 0
            THEN ROUND((CM.CARRITOS_CONVERTIDOS / CM.TOTAL_CARRITOS) * 100, 2)
            ELSE 0
        END AS TASA_ACTUAL,
        LAG(
            CASE WHEN CM.TOTAL_CARRITOS > 0 THEN ROUND((CM.CARRITOS_CONVERTIDOS / CM.TOTAL_CARRITOS) * 100, 2) ELSE 0 END, 
            1,
            NULL
        ) OVER (ORDER BY CM.MES) AS TASA_ANTERIOR
    FROM
        CONVERSION_MENSUAL CM
)
-- Recolección de resultados
SELECT
    TO_CHAR(TC.MES, 'Month YYYY', 'NLS_DATE_LANGUAGE=SPANISH') AS PERIODO,
    TC.TOTAL_CARRITOS AS TOTAL_CARRITOS,
    TC.TASA_ACTUAL AS TASA_CONVERSION,
    CASE
        WHEN TC.TASA_ANTERIOR IS NOT NULL
        THEN ROUND(TC.TASA_ACTUAL - TC.TASA_ANTERIOR, 2)
        ELSE NULL
    END AS VARIACION_TASA,
    SYSDATE AS FECHA_ACTUALIZACION
BULK COLLECT INTO RESULTADOS_KPI7
FROM
    TASAS_CALCULADAS TC
ORDER BY
    TC.MES;
IF RESULTADOS_KPI7.COUNT > 0 THEN
    FORALL i IN RESULTADOS_KPI7.FIRST .. RESULTADOS_KPI7.LAST
        INSERT INTO KPI_7 (
            PERIODO, TOTAL_CARRITOS, TASA_CONVERSION, VARIACION_TASA, FECHA_ACTUALIZACION
        )
        VALUES (
                V_KPI7_RESULTS(i).PERIODO,
                V_KPI7_RESULTS(i).TOTAL_CARRITOS,
                V_KPI7_RESULTS(i).TASA_CONVERSION,
                V_KPI7_RESULTS(i).VARIACION_TASA,
                V_KPI7_RESULTS(i).FECHA_ACTUALIZACION
            );
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('--- ERROR EN EL PROCEDIMIENTO KPI 7 ---');
        DBMS_OUTPUT.PUT_LINE('Procedimiento: ' || C_PROC_NAME);
        DBMS_OUTPUT.PUT_LINE('Código SQL: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('Mensaje SQL: ' || SQLERRM);
        RAISE;
END PROC_KPI7_CONVERSION;
/