CREATE OR REPLACE PROCEDURE PROC_REGISTROS_POR_ANIO IS

--creación de variables
TYPE tipo_conteo_anios IS TABLE OF NUMBER INDEX BY VARCHAR2(20);
V_ANIO_REG tipo_conteo_anios;

V_TOTAL_CLI NUMBER(16);
V_FECHA_REG_CLI CLIENTE.FECHA_REG_CLI%TYPE;
V_CATEGORIA_ANIO VARCHAR2(20);

-- Cursor para clientes
CURSOR C_CLIENTES IS
    SELECT FECHA_REG_CLI
    FROM CLIENTE;

BEGIN
-- Inicializar contador
V_TOTAL_CLI := 0;

-- Inicializar valores para el record
V_ANIO_REG('2020 o antes') := 0;
V_ANIO_REG('2021') := 0;
V_ANIO_REG('2022') := 0;
V_ANIO_REG('2023') := 0;
V_ANIO_REG('2024') := 0;
V_ANIO_REG('Este año') := 0;
V_ANIO_REG('Otros años') := 0;

-- Ciclo para recorrer clientes
FOR F_CLIENTE IN C_CLIENTES LOOP
    V_FECHA_REG_CLI := F_CLIENTE.FECHA_REG_CLI;

-- Determinar año de registro
V_CATEGORIA_ANIO :=
    CASE 
        WHEN EXTRACT(YEAR FROM V_FECHA_REG_CLI) <= 2020 THEN '2020 o antes'
        WHEN EXTRACT(YEAR FROM V_FECHA_REG_CLI) = 2021 THEN '2021'
        WHEN EXTRACT(YEAR FROM V_FECHA_REG_CLI) = 2022 THEN '2022'
        WHEN EXTRACT(YEAR FROM V_FECHA_REG_CLI) = 2023 THEN '2023'
        WHEN EXTRACT(YEAR FROM V_FECHA_REG_CLI) = 2024 THEN '2024'
        WHEN EXTRACT(YEAR FROM V_FECHA_REG_CLI) = EXTRACT(YEAR FROM SYSDATE) THEN 'Este año'
        ELSE 'Otros años'
END;
    V_ANIO_REG(V_CATEGORIA_ANIO) := V_ANIO_REG(V_CATEGORIA_ANIO) + 1;
    V_TOTAL_CLI := V_TOTAL_CLI + 1;
END LOOP;

--Insertar datos
INSERT INTO KPI_1 (KPI_1_ID, ANIO, TOTAL_REGISTROS)
    VALUES (KPI_1_SEQ.NEXTVAL, '2020 o antes', V_ANIO_REG('2020 o antes'));
INSERT INTO KPI_1 (KPI_1_ID, ANIO, TOTAL_REGISTROS)
    VALUES (KPI_1_SEQ.NEXTVAL, '2021', V_ANIO_REG('2021'));
INSERT INTO KPI_1 (KPI_1_ID, ANIO, TOTAL_REGISTROS)
     VALUES (KPI_1_SEQ.NEXTVAL, '2022', V_ANIO_REG('2022'));
INSERT INTO KPI_1 (KPI_1_ID, ANIO, TOTAL_REGISTROS)
    VALUES (KPI_1_SEQ.NEXTVAL, '2023', V_ANIO_REG('2023'));
INSERT INTO KPI_1 (KPI_1_ID, ANIO, TOTAL_REGISTROS)
    VALUES (KPI_1_SEQ.NEXTVAL, '2024', V_ANIO_REG('2024'));
INSERT INTO KPI_1 (KPI_1_ID, ANIO, TOTAL_REGISTROS)
    VALUES (KPI_1_SEQ.NEXTVAL, 'Este año', V_ANIO_REG('Este año'));
INSERT INTO KPI_1 (KPI_1_ID, ANIO, TOTAL_REGISTROS)
    VALUES (KPI_1_SEQ.NEXTVAL, 'Otros años', V_ANIO_REG('Otros años'));

COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END PROC_REGISTROS_POR_ANIO;
/